### PR TITLE
Add the GOST block cipher

### PR DESCRIPTION
**Pull request by agievich**

### CODE REVIEW

**Comment by ranea** [comment]
Everything looks good. Did you try to search for differential characteristic and obtain similar results as previous work (to update the table in [Primitives implemented — CASCADA 1.0.rc0 documentation](https://ranea.github.io/CASCADA/primitives_implemented.html))?

**Comment by agievich** [comment]
The following table provides the weights of best r-round differential characteristics of `GostCipher[SBOXES_CB]` found by CASCADA. Here `SBOXES_CB` is the set of GOST S-boxes described in Bruce Schneier's "Applied Cryptography" as "S-boxes used in an application for the Central Bank of the Russian Federation". This set of S-boxes is most often used in the literature on GOST. 

| r      | weight |
|--------|--------|
| 1      | 0      |
| 2      | 2      |
| 3      | 4      |
| 4      | 6.415  |
| 5      | 8.830  |
| 6      | 14.83  |
| 7      | 18.83  |
| 8      | 24.83  |
| 9      | 28.83  |
| 10     | 36.25  |
| 11     | 42.25  |
| 12     | 44.83  |
| 13     | 47.25  |
| 14     | 49.66  |
| 15     | 55.66  |
| 16     | 59.66  |
| 17     | 65.66  |

Unfortunately, despite the long history of GOST, it is difficult to find papers that could be used to verify these results. Presumably this is due to the fact that the main vector of differential attacks against GOST is based not on conventional characteristics but on aggregate and truncated differentials. In fact, the only paper found that provides specific differential characteristics is
 
> [1] Seki, H., Kaneko, T. (2001). Differential Cryptanalysis of Reduced Rounds of GOST. In: Stinson, D.R., Tavares, S. (eds) Selected Areas in Cryptography. SAC 2000. Lecture Notes in Computer Science, vol 2012. Springer, Berlin, Heidelberg. https://doi.org/10.1007/3-540-44983-3_23.

In [1], a 3-round characteristic for `GostCipher[SBOXES_CB]` of weight 10.62 is described. The characteristic is iterative and can be concatenated to cover more rounds. For example, it can be used to produce a 8-round characteristic of weight 53. This is much greater than 24.53, the weight of best 8-round characteristic found by CASCADA. CASCADA demonstrates itself as a very powerful tool.

**Comment by agievich** [comment]
The following table presents weights of best r-round linear characteristics of `GostCipher[SBOXES_CB]`. 

| r      | weight|
|--------|-------|
| 1      | 0     |
| 2      | 1     |
| 3      | 2     |
| 4      | 4.245 |
| 5      | 5.660 |
| 6      | 8.415 |
| 7      | 10.83 |
| 8      | 13.83 |
| 9      | 14.83 |
| 10     | 19.66 |
| 11     | 21.66 |
| 12     | 23.83 |
| 13     | 25.83 |
| 14     | 29.08 |
| 15     | 30.49 |
| 16     | 32.49 |

For comparison,

> [2] Lu Y. New Linear Attacks on Block Cipher GOST (https://eprint.iacr.org/2017/487)

describes a 7-round characteristic of weight 24 and 8-round characteristic of weight 30. The characteristics found by CASCADA are again significantly better.

**Comment by ranea** [comment]
Cool, glad to see CASCADA was useful to you. I'll update the documentation soon (citing this PL and these tables), and if you eventually list these tables elsewhere (a paper, or a website), I can also cite it to there.

**Pull request merged**
